### ISSUE TITLE
Implement commenting on issues

### ISSUE THREAD

**Issue by vinckr** [fjeremic/cron-first-interaction#2]
Hey, 
first of all thanks for your work here, I really like the action! 
I want to implement something like it for our repos but I also want to comment on every first issue that is created. 
Is that possible with your action? 

If not maybe I could help implement it, I am very inexperienced with Typescript but maybe it would be a good opportunity to learn.

**Comment by fjeremic** [comment]
Hi @vinckr, sorry I totally missed this in the flurry of notifications last week. Sure, that sounds like a reasonable addition. Commenting on issues is currently not implemented, but I would be happy to accept a contribution under an option.

If you take a look at the upstream non-cron based repository:
https://github.com/actions/first-interaction/blob/main/src/main.ts

You can see they have commenting on issues implemented there. You can use that as a reference to implement the cron version. Currently there is no tests here (nor in the upstream repo) so you'll have to test it out manually on some scrap repo which you can create.

**Comment by vinckr** [comment]
Alright cool :), 
I already started looking into it a little bit, but I have to do it on the side. 
I will link a PR as soon as I have something more concrete.

**Comment by vinckr** [comment]
Hello, sorry I have not really found the time to work on it after all... 
Will be closing as I am also not using the action anymore, 
thanks!
